<a href="https://colab.research.google.com/github/Henry1989-GMC/https-drive.google.com-file-d-1bsBTj7ov8cWyg0VgHANd54AY2juMeHX3-view-usp-sharing/blob/main/grades_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import numpy
import numpy as np


In [ ]:
# assign the array to a variable "grades"
grades=np.array( [85, 90, 88, 92, 95, 80, 75, 98, 89, 83])

In [ ]:
#Calculating the mean of the array
np.mean(grades)

87.5

In [ ]:
#Calculating the median of the array
np.median(grades)

88.5

In [ ]:
# Calculating the standard deviation of the array
np.std(grades)

6.591661399070799

In [ ]:
#Maximum grade of the array
np.max(grades)

98

In [ ]:
#Minimum grade of the array
np.min(grades)

75

In [ ]:
# Arranging the grades in ascending order
np.sort(grades)

array([75, 80, 83, 85, 88, 89, 90, 92, 95, 98])

In [ ]:
#Showing the position of the highest grade
np.argmax(grades)

7

In [38]:
# Showing the number of grades which are greater than 90
np.count_nonzero(grades>90)

3

In [47]:
# showing the percentage of grades greater than 90
percentage_above_90=np.mean(grades>90)*100
percentage_above_90

30.0

In [41]:
# showing the percentage of grades greater than 90
np.count_nonzero(grades>90)/len(grades)*100

30.0

In [42]:
# showing the percentage of grades less than 75
percentage_below_75=np.mean(grades<75)*100
percentage_below_75

0.0

In [45]:
#Extracting all the grades above 90 assigning them to a variable "high performers"
high_performers = grades[grades > 90]
high_performers

array([92, 95, 98])

In [46]:
#Extracting all the grades above 75 assigning them to a variable "passing grades"
passing_grades = grades[grades > 75]
passing_grades

array([85, 90, 88, 92, 95, 80, 98, 89, 83])